### PR TITLE
Locale for zhCN

### PR DESCRIPTION
**Pull request by LiangYuxuan**
Thanks to the awesome addon! This is the locale string for zhCN :)

### CODE REVIEW

**Comment by suspectz** [comment]
I've added this from a previous report, and some changes to the rank in 1.6. Can you confirm if the latest version fixes this for you?

Thanks in advance.

**Comment by LiangYuxuan** [comment]
I tired v1.6 and found some bugs. I've fixed them and updated zhCN locale for config.

**Review by suspectz — COMMENTED** [review]
Is this hook working for you? It appears to not run for me.

**Comment by LiangYuxuan** [comment]
Yes, it works good for me, both enabling Corruption Tooltips only or with ElvUI.

微信图片_20200213223300

**Comment by LiangYuxuan** [comment]
Er, I found you revent the hook method commit. Actually, hooking a global function which is OnEnter method won't work as expected. You can find it on [hooksecurefunc](https://wow.gamepedia.com/API_hooksecurefunc) 's wiki page, which is in notes.

I went into a issue like hooking failure on a character who equited only one corruption gear, and I found this. Should be `> 0`, and looks like hooking failure.
https://github.com/suspectz/Corruption-Tooltips/blob/06f32701d6ab6d68246dfe7981d061e98446bc6c/CorruptionTooltips.lua#L119

**Comment by suspectz** [comment]
Makes sense. I can't get SecureHookScript to work at all with my client, the event does not trigger. I can commit what I've got, but I wanted to get a fixed config and GUI out, which is why I didn't include it. That is `self:SecureHookScript(CharacterStatsPane.ItemLevelFrame.Corruption, 'OnEnter', 'SummaryHook')` does not appear to hook as expected.

Ok, so it appears the Narcissus addon breaks that Frame.

**Comment by suspectz** [comment]
Sorry. You're absolutely right. It does work, its some other addon tainting the event.

**Pull request merged**
